### ISSUE TITLE
ROR group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ahmedeid6842** [ahmedeid6842/Recipe_App#13]
# ROR group capstone: set up your Kanban board

https://github.com/ahmedeid6842/Recipe_App/projects/1

### Hello! We are a team composed of two people: Cesar and Ahmed

**The following team distribution was established:**

- `Team member #1`: @CesarHerr 
- `Team member #2`: @ahmedeid6842

**Comment by Munsa1** [comment]
Hi @ahmedeid6842 @CesarHerr, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Equal Distribution Of WorkLoad :heavy_check_mark: 
Descriptive Card Descriptions :heavy_check_mark: 
Methodical Breakdown Of Tasks ✔️ 

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
